### PR TITLE
fix errors in flutter 3.16.0

### PR DESCRIPTION
**Pull request by moweiran**

### CODE REVIEW

**Comment by NamanShergill** [comment]
This won't compile without `extended_text_library` being updated too

**Comment by zmtzawqlp** [comment]
migrate to Flutter 3.16.0 later

**Comment by ChanNagihong** [comment]
Why **extended_text_field** is not published yet? **extended_text_library** is compatible with Flutter 3.16.0 now.

**Comment by zmtzawqlp** [comment]
> Why **extended_text_field** is not published yet? **extended_text_library** is compatible with Flutter 3.16.0 now.

some issues on 3.16.0

**Comment by zmtzawqlp** [comment]
done

**Pull request closed without merging**
